version: '3.8'
services:
  jupyterlab:
    user: root
    build:
      context: ./docker/jupyterlab
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=True
      - CHOWN_HOME=True
      - CHOWN_HOME_OPTS=-R
      - GRANT_SUDO='yes'

  streamlit:
    build:
      context: ./docker/streamlit
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    command: streamlit run app.py --server.address="0.0.0.0"
    volumes:
      - ./app:/app
